Community.create!([
  {community_area: 1, community_area_name: "Rogers Park"},
  {community_area: 2, community_area_name: "West Ridge"},
  {community_area: 3, community_area_name: "Uptown"},
  {community_area: 4, community_area_name: "Lincoln Square"},
  {community_area: 5, community_area_name: "North Center"},
  {community_area: 6, community_area_name: "Lakeview"},
  {community_area: 7, community_area_name: "Lincoln Park"},
  {community_area: 8, community_area_name: "Near North Side"},
  {community_area: 9, community_area_name: "Edison Park"},
  {community_area: 10, community_area_name: "Norwood Park"},
  {community_area: 11, community_area_name: "Jefferson Park"},
  {community_area: 12, community_area_name: "Forest Glen"},
  {community_area: 13, community_area_name: "North Park"},
  {community_area: 14, community_area_name: "Albany Park"},
  {community_area: 15, community_area_name: "Portage Park"},
  {community_area: 16, community_area_name: "Irving Park"},
  {community_area: 17, community_area_name: "Dunning"},
  {community_area: 18, community_area_name: "Montclare "},
  {community_area: 19, community_area_name: "Belmont Cragin"},
  {community_area: 20, community_area_name: "Hermosa"},
  {community_area: 21, community_area_name: "Avondale"},
  {community_area: 22, community_area_name: "Logan Square"},
  {community_area: 23, community_area_name: "Humboldt Park"},
  {community_area: 24, community_area_name: "West Town"},
  {community_area: 25, community_area_name: "Austin"},
  {community_area: 26, community_area_name: "West Garfield Park"},
  {community_area: 27, community_area_name: "East Garfield Park"},
  {community_area: 28, community_area_name: "Near West Side"},
  {community_area: 29, community_area_name: "North Lawndale"},
  {community_area: 30, community_area_name: "South Lawndale"},
  {community_area: 31, community_area_name: "Lower West Side"},
  {community_area: 32, community_area_name: "Loop"},
  {community_area: 33, community_area_name: "Near South Side"},
  {community_area: 34, community_area_name: "Armour Square"},
  {community_area: 35, community_area_name: "Douglas "},
  {community_area: 36, community_area_name: "Oakland"},
  {community_area: 37, community_area_name: "Fuller Park"},
  {community_area: 38, community_area_name: "Grand Boulevard"},
  {community_area: 39, community_area_name: "Kenwood"},
  {community_area: 40, community_area_name: "Washington Park"},
  {community_area: 41, community_area_name: "Hyde Park"},
  {community_area: 42, community_area_name: "Woodlawn"},
  {community_area: 43, community_area_name: "South Shore"},
  {community_area: 44, community_area_name: "Chatham"},
  {community_area: 45, community_area_name: "Avalon Park"},
  {community_area: 46, community_area_name: "South Chicago"},
  {community_area: 47, community_area_name: "Burnside"},
  {community_area: 48, community_area_name: "Calumet Heights"},
  {community_area: 49, community_area_name: "Roseland"},
  {community_area: 50, community_area_name: "Pullman"},
  {community_area: 51, community_area_name: "South Deering"},
  {community_area: 52, community_area_name: "East Side"},
  {community_area: 53, community_area_name: "West Pullman"},
  {community_area: 54, community_area_name: "Riverdale"},
  {community_area: 55, community_area_name: "Hegewisch"},
  {community_area: 56, community_area_name: "Garfield Ridge"},
  {community_area: 57, community_area_name: "Archer Heights"},
  {community_area: 58, community_area_name: "Brighton Park"},
  {community_area: 59, community_area_name: "McKinley Park"},
  {community_area: 60, community_area_name: "Bridgeport"},
  {community_area: 61, community_area_name: "New City"},
  {community_area: 62, community_area_name: "West Elsdon"},
  {community_area: 63, community_area_name: "Gage Park"},
  {community_area: 64, community_area_name: "Clearing"},
  {community_area: 65, community_area_name: "West Lawn"},
  {community_area: 66, community_area_name: "Chicago Lawn"},
  {community_area: 67, community_area_name: "West Englewood"},
  {community_area: 68, community_area_name: "Englewood"},
  {community_area: 69, community_area_name: "Greater Grand Crossing"},
  {community_area: 70, community_area_name: "Ashburn"},
  {community_area: 71, community_area_name: "Auburn Gresham"},
  {community_area: 72, community_area_name: "Beverly"},
  {community_area: 73, community_area_name: "Washington Heights"},
  {community_area: 74, community_area_name: "Mount Greenwood"},
  {community_area: 75, community_area_name: "Morgan Park"},
  {community_area: 76, community_area_name: "O'Hare"},
  {community_area: 77, community_area_name: "Edgewater"}
])
LifeExpectancy.create!([
  {community_area: 1, community_area_name: "Rogers Park", life_expectancy_1990: 71, life_expectancy_2000: 73, life_expectancy_2010: 77},
  {community_area: 2, community_area_name: "West Ridge", life_expectancy_1990: 77, life_expectancy_2000: 78, life_expectancy_2010: 80},
  {community_area: 3, community_area_name: "Uptown", life_expectancy_1990: 64, life_expectancy_2000: 72, life_expectancy_2010: 76},
  {community_area: 4, community_area_name: "Lincoln Square", life_expectancy_1990: 74, life_expectancy_2000: 77, life_expectancy_2010: 81},
  {community_area: 5, community_area_name: "North Center", life_expectancy_1990: 73, life_expectancy_2000: 78, life_expectancy_2010: 82},
  {community_area: 6, community_area_name: "Lakeview", life_expectancy_1990: 74, life_expectancy_2000: 79, life_expectancy_2010: 82},
  {community_area: 7, community_area_name: "Lincoln Park", life_expectancy_1990: 74, life_expectancy_2000: 77, life_expectancy_2010: 81},
  {community_area: 8, community_area_name: "Near North Side", life_expectancy_1990: 75, life_expectancy_2000: 80, life_expectancy_2010: 85},
  {community_area: 9, community_area_name: "Edison Park", life_expectancy_1990: 78, life_expectancy_2000: 79, life_expectancy_2010: 81},
  {community_area: 10, community_area_name: "Norwood Park", life_expectancy_1990: 77, life_expectancy_2000: 78, life_expectancy_2010: 81},
  {community_area: 11, community_area_name: "Jefferson Park", life_expectancy_1990: 77, life_expectancy_2000: 79, life_expectancy_2010: 80},
  {community_area: 12, community_area_name: "Forest Glen", life_expectancy_1990: 79, life_expectancy_2000: 81, life_expectancy_2010: 83},
  {community_area: 13, community_area_name: "North Park", life_expectancy_1990: 77, life_expectancy_2000: 79, life_expectancy_2010: 84},
  {community_area: 14, community_area_name: "Albany Park", life_expectancy_1990: 74, life_expectancy_2000: 78, life_expectancy_2010: 81},
  {community_area: 15, community_area_name: "Portage Park", life_expectancy_1990: 75, life_expectancy_2000: 76, life_expectancy_2010: 80},
  {community_area: 16, community_area_name: "Irving Park", life_expectancy_1990: 75, life_expectancy_2000: 77, life_expectancy_2010: 80},
  {community_area: 17, community_area_name: "Dunning", life_expectancy_1990: 77, life_expectancy_2000: 79, life_expectancy_2010: 80},
  {community_area: 18, community_area_name: "Montclare ", life_expectancy_1990: 77, life_expectancy_2000: 79, life_expectancy_2010: 80},
  {community_area: 19, community_area_name: "Belmont Cragin", life_expectancy_1990: 74, life_expectancy_2000: 76, life_expectancy_2010: 80},
  {community_area: 20, community_area_name: "Hermosa", life_expectancy_1990: 74, life_expectancy_2000: 78, life_expectancy_2010: 81},
  {community_area: 21, community_area_name: "Avondale", life_expectancy_1990: 74, life_expectancy_2000: 78, life_expectancy_2010: 80},
  {community_area: 22, community_area_name: "Logan Square", life_expectancy_1990: 72, life_expectancy_2000: 75, life_expectancy_2010: 80},
  {community_area: 23, community_area_name: "Humboldt Park", life_expectancy_1990: 68, life_expectancy_2000: 71, life_expectancy_2010: 75},
  {community_area: 24, community_area_name: "West Town", life_expectancy_1990: 71, life_expectancy_2000: 76, life_expectancy_2010: 80},
  {community_area: 25, community_area_name: "Austin", life_expectancy_1990: 66, life_expectancy_2000: 70, life_expectancy_2010: 72},
  {community_area: 26, community_area_name: "West Garfield Park", life_expectancy_1990: 63, life_expectancy_2000: 67, life_expectancy_2010: 69},
  {community_area: 27, community_area_name: "East Garfield Park", life_expectancy_1990: 62, life_expectancy_2000: 66, life_expectancy_2010: 72},
  {community_area: 28, community_area_name: "Near West Side", life_expectancy_1990: 64, life_expectancy_2000: 73, life_expectancy_2010: 79},
  {community_area: 29, community_area_name: "North Lawndale", life_expectancy_1990: 62, life_expectancy_2000: 67, life_expectancy_2010: 72},
  {community_area: 30, community_area_name: "South Lawndale", life_expectancy_1990: 73, life_expectancy_2000: 77, life_expectancy_2010: 82},
  {community_area: 31, community_area_name: "Lower West Side", life_expectancy_1990: 74, life_expectancy_2000: 77, life_expectancy_2010: 81},
  {community_area: 32, community_area_name: "Loop", life_expectancy_1990: 74, life_expectancy_2000: 81, life_expectancy_2010: 85},
  {community_area: 33, community_area_name: "Near South Side", life_expectancy_1990: 60, life_expectancy_2000: 68, life_expectancy_2010: 81},
  {community_area: 34, community_area_name: "Armour Square", life_expectancy_1990: 75, life_expectancy_2000: 77, life_expectancy_2010: 82},
  {community_area: 35, community_area_name: "Douglas ", life_expectancy_1990: 65, life_expectancy_2000: 66, life_expectancy_2010: 74},
  {community_area: 36, community_area_name: "Oakland", life_expectancy_1990: 60, life_expectancy_2000: 68, life_expectancy_2010: 74},
  {community_area: 37, community_area_name: "Fuller Park", life_expectancy_1990: 60, life_expectancy_2000: 66, life_expectancy_2010: 70},
  {community_area: 38, community_area_name: "Grand Boulevard", life_expectancy_1990: 57, life_expectancy_2000: 64, life_expectancy_2010: 74},
  {community_area: 39, community_area_name: "Kenwood", life_expectancy_1990: 68, life_expectancy_2000: 74, life_expectancy_2010: 81},
  {community_area: 40, community_area_name: "Washington Park", life_expectancy_1990: 58, life_expectancy_2000: 64, life_expectancy_2010: 69},
  {community_area: 41, community_area_name: "Hyde Park", life_expectancy_1990: 75, life_expectancy_2000: 82, life_expectancy_2010: 82},
  {community_area: 42, community_area_name: "Woodlawn", life_expectancy_1990: 63, life_expectancy_2000: 69, life_expectancy_2010: 75},
  {community_area: 43, community_area_name: "South Shore", life_expectancy_1990: 68, life_expectancy_2000: 70, life_expectancy_2010: 73},
  {community_area: 44, community_area_name: "Chatham", life_expectancy_1990: 71, life_expectancy_2000: 71, life_expectancy_2010: 74},
  {community_area: 45, community_area_name: "Avalon Park", life_expectancy_1990: 68, life_expectancy_2000: 73, life_expectancy_2010: 75},
  {community_area: 46, community_area_name: "South Chicago", life_expectancy_1990: 70, life_expectancy_2000: 71, life_expectancy_2010: 73},
  {community_area: 47, community_area_name: "Burnside", life_expectancy_1990: 71, life_expectancy_2000: 71, life_expectancy_2010: 72},
  {community_area: 48, community_area_name: "Calumet Heights", life_expectancy_1990: 72, life_expectancy_2000: 73, life_expectancy_2010: 77},
  {community_area: 49, community_area_name: "Roseland", life_expectancy_1990: 67, life_expectancy_2000: 70, life_expectancy_2010: 73},
  {community_area: 50, community_area_name: "Pullman", life_expectancy_1990: 68, life_expectancy_2000: 71, life_expectancy_2010: 76},
  {community_area: 51, community_area_name: "South Deering", life_expectancy_1990: 71, life_expectancy_2000: 73, life_expectancy_2010: 76},
  {community_area: 52, community_area_name: "East Side", life_expectancy_1990: 73, life_expectancy_2000: 76, life_expectancy_2010: 78},
  {community_area: 53, community_area_name: "West Pullman", life_expectancy_1990: 68, life_expectancy_2000: 70, life_expectancy_2010: 72},
  {community_area: 54, community_area_name: "Riverdale", life_expectancy_1990: 68, life_expectancy_2000: 70, life_expectancy_2010: 76},
  {community_area: 55, community_area_name: "Hegewisch", life_expectancy_1990: 73, life_expectancy_2000: 73, life_expectancy_2010: 77},
  {community_area: 56, community_area_name: "Garfield Ridge", life_expectancy_1990: 75, life_expectancy_2000: 77, life_expectancy_2010: 80},
  {community_area: 57, community_area_name: "Archer Heights", life_expectancy_1990: 73, life_expectancy_2000: 77, life_expectancy_2010: 80},
  {community_area: 58, community_area_name: "Brighton Park", life_expectancy_1990: 71, life_expectancy_2000: 77, life_expectancy_2010: 81},
  {community_area: 59, community_area_name: "McKinley Park", life_expectancy_1990: 72, life_expectancy_2000: 75, life_expectancy_2010: 80},
  {community_area: 60, community_area_name: "Bridgeport", life_expectancy_1990: 73, life_expectancy_2000: 76, life_expectancy_2010: 80},
  {community_area: 61, community_area_name: "New City", life_expectancy_1990: 66, life_expectancy_2000: 72, life_expectancy_2010: 74},
  {community_area: 62, community_area_name: "West Elsdon", life_expectancy_1990: 76, life_expectancy_2000: 75, life_expectancy_2010: 81},
  {community_area: 63, community_area_name: "Gage Park", life_expectancy_1990: 73, life_expectancy_2000: 77, life_expectancy_2010: 79},
  {community_area: 64, community_area_name: "Clearing", life_expectancy_1990: 74, life_expectancy_2000: 76, life_expectancy_2010: 78},
  {community_area: 65, community_area_name: "West Lawn", life_expectancy_1990: 75, life_expectancy_2000: 75, life_expectancy_2010: 81},
  {community_area: 66, community_area_name: "Chicago Lawn", life_expectancy_1990: 73, life_expectancy_2000: 74, life_expectancy_2010: 75},
  {community_area: 67, community_area_name: "West Englewood", life_expectancy_1990: 65, life_expectancy_2000: 67, life_expectancy_2010: 70},
  {community_area: 68, community_area_name: "Englewood", life_expectancy_1990: 62, life_expectancy_2000: 67, life_expectancy_2010: 71},
  {community_area: 69, community_area_name: "Greater Grand Crossing", life_expectancy_1990: 66, life_expectancy_2000: 69, life_expectancy_2010: 71},
  {community_area: 70, community_area_name: "Ashburn", life_expectancy_1990: 74, life_expectancy_2000: 74, life_expectancy_2010: 78},
  {community_area: 71, community_area_name: "Auburn Gresham", life_expectancy_1990: 68, life_expectancy_2000: 69, life_expectancy_2010: 73},
  {community_area: 72, community_area_name: "Beverly", life_expectancy_1990: 76, life_expectancy_2000: 79, life_expectancy_2010: 81},
  {community_area: 73, community_area_name: "Washington Heights", life_expectancy_1990: 69, life_expectancy_2000: 71, life_expectancy_2010: 75},
  {community_area: 74, community_area_name: "Mount Greenwood", life_expectancy_1990: 76, life_expectancy_2000: 76, life_expectancy_2010: 80},
  {community_area: 75, community_area_name: "Morgan Park", life_expectancy_1990: 72, life_expectancy_2000: 73, life_expectancy_2010: 75},
  {community_area: 76, community_area_name: "O'Hare", life_expectancy_1990: 79, life_expectancy_2000: 80, life_expectancy_2010: 82},
  {community_area: 77, community_area_name: "Edgewater", life_expectancy_1990: 78, life_expectancy_2000: 77, life_expectancy_2010: 80},
  {community_area: nil, community_area_name: "CHICAGO ", life_expectancy_1990: 71, life_expectancy_2000: 74, life_expectancy_2010: 78}
])
SocioEconomicIndicator.create!([
  {community_area: 1, community_area_name: "Rogers Park", percent_of_housing_crowded: 8, percent_households_below_poverty: 24, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 18, percent_under_18_over_64: 28, per_capita_income: 23939, hardship_index: 39},
  {community_area: 2, community_area_name: "West Ridge", percent_of_housing_crowded: 8, percent_households_below_poverty: 17, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 21, percent_under_18_over_64: 39, per_capita_income: 23040, hardship_index: 46},
  {community_area: 3, community_area_name: "Uptown", percent_of_housing_crowded: 4, percent_households_below_poverty: 24, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 12, percent_under_18_over_64: 22, per_capita_income: 35787, hardship_index: 20},
  {community_area: 4, community_area_name: "Lincoln Square", percent_of_housing_crowded: 3, percent_households_below_poverty: 11, percent_over_16_unemployed: 8, percent_over_25_without_HS_diploma: 13, percent_under_18_over_64: 26, per_capita_income: 37524, hardship_index: 17},
  {community_area: 5, community_area_name: "North Center", percent_of_housing_crowded: 0, percent_households_below_poverty: 8, percent_over_16_unemployed: 5, percent_over_25_without_HS_diploma: 5, percent_under_18_over_64: 26, per_capita_income: 57123, hardship_index: 6},
  {community_area: 6, community_area_name: "Lake View", percent_of_housing_crowded: 1, percent_households_below_poverty: 11, percent_over_16_unemployed: 5, percent_over_25_without_HS_diploma: 3, percent_under_18_over_64: 17, per_capita_income: 60058, hardship_index: 5},
  {community_area: 7, community_area_name: "Lincoln Park", percent_of_housing_crowded: 1, percent_households_below_poverty: 12, percent_over_16_unemployed: 5, percent_over_25_without_HS_diploma: 4, percent_under_18_over_64: 22, per_capita_income: 71551, hardship_index: 2},
  {community_area: 8, community_area_name: "Near North Side", percent_of_housing_crowded: 2, percent_households_below_poverty: 13, percent_over_16_unemployed: 7, percent_over_25_without_HS_diploma: 3, percent_under_18_over_64: 23, per_capita_income: 88669, hardship_index: 1},
  {community_area: 9, community_area_name: "Edison Park", percent_of_housing_crowded: 1, percent_households_below_poverty: 3, percent_over_16_unemployed: 7, percent_over_25_without_HS_diploma: 7, percent_under_18_over_64: 35, per_capita_income: 40959, hardship_index: 8},
  {community_area: 10, community_area_name: "Norwood Park", percent_of_housing_crowded: 2, percent_households_below_poverty: 5, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 12, percent_under_18_over_64: 40, per_capita_income: 32875, hardship_index: 21},
  {community_area: 11, community_area_name: "Jefferson Park", percent_of_housing_crowded: 3, percent_households_below_poverty: 9, percent_over_16_unemployed: 12, percent_over_25_without_HS_diploma: 13, percent_under_18_over_64: 36, per_capita_income: 27751, hardship_index: 25},
  {community_area: 12, community_area_name: "Forest Glen", percent_of_housing_crowded: 1, percent_households_below_poverty: 8, percent_over_16_unemployed: 7, percent_over_25_without_HS_diploma: 5, percent_under_18_over_64: 41, per_capita_income: 44164, hardship_index: 11},
  {community_area: 13, community_area_name: "North Park", percent_of_housing_crowded: 4, percent_households_below_poverty: 13, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 14, percent_under_18_over_64: 39, per_capita_income: 26576, hardship_index: 33},
  {community_area: 14, community_area_name: "Albany Park", percent_of_housing_crowded: 11, percent_households_below_poverty: 19, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 33, percent_under_18_over_64: 32, per_capita_income: 21323, hardship_index: 53},
  {community_area: 15, community_area_name: "Portage Park", percent_of_housing_crowded: 4, percent_households_below_poverty: 12, percent_over_16_unemployed: 13, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 34, per_capita_income: 24336, hardship_index: 35},
  {community_area: 16, community_area_name: "Irving Park", percent_of_housing_crowded: 6, percent_households_below_poverty: 13, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 22, percent_under_18_over_64: 32, per_capita_income: 27249, hardship_index: 34},
  {community_area: 17, community_area_name: "Dunning", percent_of_housing_crowded: 5, percent_households_below_poverty: 11, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 16, percent_under_18_over_64: 34, per_capita_income: 26282, hardship_index: 28},
  {community_area: 18, community_area_name: "Montclaire", percent_of_housing_crowded: 8, percent_households_below_poverty: 15, percent_over_16_unemployed: 14, percent_over_25_without_HS_diploma: 24, percent_under_18_over_64: 39, per_capita_income: 22014, hardship_index: 50},
  {community_area: 19, community_area_name: "Belmont Cragin", percent_of_housing_crowded: 11, percent_households_below_poverty: 19, percent_over_16_unemployed: 15, percent_over_25_without_HS_diploma: 37, percent_under_18_over_64: 37, per_capita_income: 15461, hardship_index: 70},
  {community_area: 20, community_area_name: "Hermosa", percent_of_housing_crowded: 7, percent_households_below_poverty: 21, percent_over_16_unemployed: 13, percent_over_25_without_HS_diploma: 42, percent_under_18_over_64: 36, per_capita_income: 15089, hardship_index: 71},
  {community_area: 21, community_area_name: "Avondale", percent_of_housing_crowded: 6, percent_households_below_poverty: 15, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 25, percent_under_18_over_64: 31, per_capita_income: 20039, hardship_index: 42},
  {community_area: 22, community_area_name: "Logan Square", percent_of_housing_crowded: 3, percent_households_below_poverty: 17, percent_over_16_unemployed: 8, percent_over_25_without_HS_diploma: 15, percent_under_18_over_64: 26, per_capita_income: 31908, hardship_index: 23},
  {community_area: 23, community_area_name: "Humboldt park", percent_of_housing_crowded: 15, percent_households_below_poverty: 34, percent_over_16_unemployed: 17, percent_over_25_without_HS_diploma: 35, percent_under_18_over_64: 38, per_capita_income: 13781, hardship_index: 85},
  {community_area: 24, community_area_name: "West Town", percent_of_housing_crowded: 2, percent_households_below_poverty: 15, percent_over_16_unemployed: 7, percent_over_25_without_HS_diploma: 13, percent_under_18_over_64: 22, per_capita_income: 43198, hardship_index: 10},
  {community_area: 25, community_area_name: "Austin", percent_of_housing_crowded: 6, percent_households_below_poverty: 29, percent_over_16_unemployed: 23, percent_over_25_without_HS_diploma: 24, percent_under_18_over_64: 38, per_capita_income: 15957, hardship_index: 73},
  {community_area: 26, community_area_name: "West Garfield Park", percent_of_housing_crowded: 9, percent_households_below_poverty: 42, percent_over_16_unemployed: 26, percent_over_25_without_HS_diploma: 25, percent_under_18_over_64: 44, per_capita_income: 10934, hardship_index: 92},
  {community_area: 27, community_area_name: "East Garfield Park", percent_of_housing_crowded: 8, percent_households_below_poverty: 42, percent_over_16_unemployed: 20, percent_over_25_without_HS_diploma: 21, percent_under_18_over_64: 43, per_capita_income: 12961, hardship_index: 83},
  {community_area: 28, community_area_name: "Near West Side", percent_of_housing_crowded: 4, percent_households_below_poverty: 21, percent_over_16_unemployed: 11, percent_over_25_without_HS_diploma: 10, percent_under_18_over_64: 22, per_capita_income: 44689, hardship_index: 15},
  {community_area: 29, community_area_name: "North Lawndale", percent_of_housing_crowded: 7, percent_households_below_poverty: 43, percent_over_16_unemployed: 21, percent_over_25_without_HS_diploma: 28, percent_under_18_over_64: 43, per_capita_income: 12034, hardship_index: 87},
  {community_area: 30, community_area_name: "South Lawndale", percent_of_housing_crowded: 15, percent_households_below_poverty: 31, percent_over_16_unemployed: 16, percent_over_25_without_HS_diploma: 55, percent_under_18_over_64: 34, per_capita_income: 10402, hardship_index: 96},
  {community_area: 31, community_area_name: "Lower West Side", percent_of_housing_crowded: 10, percent_households_below_poverty: 26, percent_over_16_unemployed: 16, percent_over_25_without_HS_diploma: 41, percent_under_18_over_64: 33, per_capita_income: 16444, hardship_index: 76},
  {community_area: 32, community_area_name: "Loop", percent_of_housing_crowded: 2, percent_households_below_poverty: 15, percent_over_16_unemployed: 6, percent_over_25_without_HS_diploma: 3, percent_under_18_over_64: 14, per_capita_income: 65526, hardship_index: 3},
  {community_area: 33, community_area_name: "Near South Side", percent_of_housing_crowded: 1, percent_households_below_poverty: 14, percent_over_16_unemployed: 5, percent_over_25_without_HS_diploma: 7, percent_under_18_over_64: 22, per_capita_income: 59077, hardship_index: 7},
  {community_area: 34, community_area_name: "Armour Square", percent_of_housing_crowded: 6, percent_households_below_poverty: 40, percent_over_16_unemployed: 17, percent_over_25_without_HS_diploma: 35, percent_under_18_over_64: 38, per_capita_income: 16148, hardship_index: 82},
  {community_area: 35, community_area_name: "Douglas", percent_of_housing_crowded: 2, percent_households_below_poverty: 30, percent_over_16_unemployed: 18, percent_over_25_without_HS_diploma: 14, percent_under_18_over_64: 31, per_capita_income: 23791, hardship_index: 47},
  {community_area: 36, community_area_name: "Oakland", percent_of_housing_crowded: 1, percent_households_below_poverty: 40, percent_over_16_unemployed: 29, percent_over_25_without_HS_diploma: 18, percent_under_18_over_64: 40, per_capita_income: 19252, hardship_index: 78},
  {community_area: 37, community_area_name: "Fuller Park", percent_of_housing_crowded: 3, percent_households_below_poverty: 51, percent_over_16_unemployed: 34, percent_over_25_without_HS_diploma: 27, percent_under_18_over_64: 45, per_capita_income: 10432, hardship_index: 97},
  {community_area: 38, community_area_name: "Grand Boulevard", percent_of_housing_crowded: 3, percent_households_below_poverty: 29, percent_over_16_unemployed: 24, percent_over_25_without_HS_diploma: 16, percent_under_18_over_64: 40, per_capita_income: 23472, hardship_index: 57},
  {community_area: 39, community_area_name: "Kenwood", percent_of_housing_crowded: 2, percent_households_below_poverty: 22, percent_over_16_unemployed: 16, percent_over_25_without_HS_diploma: 11, percent_under_18_over_64: 35, per_capita_income: 35911, hardship_index: 26},
  {community_area: 40, community_area_name: "Washington Park", percent_of_housing_crowded: 6, percent_households_below_poverty: 42, percent_over_16_unemployed: 29, percent_over_25_without_HS_diploma: 25, percent_under_18_over_64: 43, per_capita_income: 13785, hardship_index: 88},
  {community_area: 41, community_area_name: "Hyde Park", percent_of_housing_crowded: 2, percent_households_below_poverty: 18, percent_over_16_unemployed: 8, percent_over_25_without_HS_diploma: 4, percent_under_18_over_64: 26, per_capita_income: 39056, hardship_index: 14},
  {community_area: 42, community_area_name: "Woodlawn", percent_of_housing_crowded: 3, percent_households_below_poverty: 31, percent_over_16_unemployed: 23, percent_over_25_without_HS_diploma: 17, percent_under_18_over_64: 36, per_capita_income: 18672, hardship_index: 58},
  {community_area: 43, community_area_name: "South Shore", percent_of_housing_crowded: 3, percent_households_below_poverty: 31, percent_over_16_unemployed: 20, percent_over_25_without_HS_diploma: 14, percent_under_18_over_64: 36, per_capita_income: 19398, hardship_index: 55},
  {community_area: 44, community_area_name: "Chatham", percent_of_housing_crowded: 3, percent_households_below_poverty: 28, percent_over_16_unemployed: 24, percent_over_25_without_HS_diploma: 15, percent_under_18_over_64: 40, per_capita_income: 18881, hardship_index: 60},
  {community_area: 45, community_area_name: "Avalon Park", percent_of_housing_crowded: 1, percent_households_below_poverty: 17, percent_over_16_unemployed: 21, percent_over_25_without_HS_diploma: 11, percent_under_18_over_64: 39, per_capita_income: 24454, hardship_index: 41},
  {community_area: 46, community_area_name: "South Chicago", percent_of_housing_crowded: 5, percent_households_below_poverty: 30, percent_over_16_unemployed: 20, percent_over_25_without_HS_diploma: 27, percent_under_18_over_64: 41, per_capita_income: 16579, hardship_index: 75},
  {community_area: 47, community_area_name: "Burnside", percent_of_housing_crowded: 7, percent_households_below_poverty: 33, percent_over_16_unemployed: 19, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 43, per_capita_income: 12515, hardship_index: 79},
  {community_area: 48, community_area_name: "Calumet Heights", percent_of_housing_crowded: 2, percent_households_below_poverty: 12, percent_over_16_unemployed: 20, percent_over_25_without_HS_diploma: 11, percent_under_18_over_64: 44, per_capita_income: 28887, hardship_index: 38},
  {community_area: 49, community_area_name: "Roseland", percent_of_housing_crowded: 3, percent_households_below_poverty: 20, percent_over_16_unemployed: 20, percent_over_25_without_HS_diploma: 17, percent_under_18_over_64: 41, per_capita_income: 17949, hardship_index: 52},
  {community_area: 50, community_area_name: "Pullman", percent_of_housing_crowded: 2, percent_households_below_poverty: 22, percent_over_16_unemployed: 23, percent_over_25_without_HS_diploma: 13, percent_under_18_over_64: 39, per_capita_income: 20588, hardship_index: 51},
  {community_area: 51, community_area_name: "South Deering", percent_of_housing_crowded: 4, percent_households_below_poverty: 29, percent_over_16_unemployed: 16, percent_over_25_without_HS_diploma: 21, percent_under_18_over_64: 40, per_capita_income: 14685, hardship_index: 65},
  {community_area: 52, community_area_name: "East Side", percent_of_housing_crowded: 7, percent_households_below_poverty: 19, percent_over_16_unemployed: 12, percent_over_25_without_HS_diploma: 32, percent_under_18_over_64: 43, per_capita_income: 17104, hardship_index: 64},
  {community_area: 53, community_area_name: "West Pullman", percent_of_housing_crowded: 3, percent_households_below_poverty: 26, percent_over_16_unemployed: 19, percent_over_25_without_HS_diploma: 21, percent_under_18_over_64: 42, per_capita_income: 16563, hardship_index: 62},
  {community_area: 54, community_area_name: "Riverdale", percent_of_housing_crowded: 6, percent_households_below_poverty: 57, percent_over_16_unemployed: 35, percent_over_25_without_HS_diploma: 28, percent_under_18_over_64: 52, per_capita_income: 8201, hardship_index: 98},
  {community_area: 55, community_area_name: "Hegewisch", percent_of_housing_crowded: 3, percent_households_below_poverty: 17, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 43, per_capita_income: 22677, hardship_index: 44},
  {community_area: 56, community_area_name: "Garfield Ridge", percent_of_housing_crowded: 3, percent_households_below_poverty: 9, percent_over_16_unemployed: 11, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 38, per_capita_income: 26353, hardship_index: 32},
  {community_area: 57, community_area_name: "Archer Heights", percent_of_housing_crowded: 9, percent_households_below_poverty: 14, percent_over_16_unemployed: 17, percent_over_25_without_HS_diploma: 36, percent_under_18_over_64: 39, per_capita_income: 16134, hardship_index: 67},
  {community_area: 58, community_area_name: "Brighton Park", percent_of_housing_crowded: 14, percent_households_below_poverty: 24, percent_over_16_unemployed: 14, percent_over_25_without_HS_diploma: 45, percent_under_18_over_64: 39, per_capita_income: 13089, hardship_index: 84},
  {community_area: 59, community_area_name: "McKinley Park", percent_of_housing_crowded: 7, percent_households_below_poverty: 19, percent_over_16_unemployed: 13, percent_over_25_without_HS_diploma: 33, percent_under_18_over_64: 36, per_capita_income: 16954, hardship_index: 61},
  {community_area: 60, community_area_name: "Bridgeport", percent_of_housing_crowded: 5, percent_households_below_poverty: 19, percent_over_16_unemployed: 14, percent_over_25_without_HS_diploma: 22, percent_under_18_over_64: 31, per_capita_income: 22694, hardship_index: 43},
  {community_area: 61, community_area_name: "New City", percent_of_housing_crowded: 12, percent_households_below_poverty: 29, percent_over_16_unemployed: 23, percent_over_25_without_HS_diploma: 42, percent_under_18_over_64: 39, per_capita_income: 12765, hardship_index: 91},
  {community_area: 62, community_area_name: "West Elsdon", percent_of_housing_crowded: 11, percent_households_below_poverty: 16, percent_over_16_unemployed: 17, percent_over_25_without_HS_diploma: 37, percent_under_18_over_64: 38, per_capita_income: 15754, hardship_index: 69},
  {community_area: 63, community_area_name: "Gage Park", percent_of_housing_crowded: 16, percent_households_below_poverty: 23, percent_over_16_unemployed: 18, percent_over_25_without_HS_diploma: 52, percent_under_18_over_64: 39, per_capita_income: 12171, hardship_index: 93},
  {community_area: 64, community_area_name: "Clearing", percent_of_housing_crowded: 3, percent_households_below_poverty: 9, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 38, per_capita_income: 25113, hardship_index: 29},
  {community_area: 65, community_area_name: "West Lawn", percent_of_housing_crowded: 6, percent_households_below_poverty: 15, percent_over_16_unemployed: 10, percent_over_25_without_HS_diploma: 34, percent_under_18_over_64: 40, per_capita_income: 16907, hardship_index: 56},
  {community_area: 66, community_area_name: "Chicago Lawn", percent_of_housing_crowded: 8, percent_households_below_poverty: 28, percent_over_16_unemployed: 17, percent_over_25_without_HS_diploma: 31, percent_under_18_over_64: 41, per_capita_income: 13231, hardship_index: 80},
  {community_area: 67, community_area_name: "West Englewood", percent_of_housing_crowded: 5, percent_households_below_poverty: 34, percent_over_16_unemployed: 36, percent_over_25_without_HS_diploma: 26, percent_under_18_over_64: 41, per_capita_income: 11317, hardship_index: 89},
  {community_area: 68, community_area_name: "Englewood", percent_of_housing_crowded: 4, percent_households_below_poverty: 47, percent_over_16_unemployed: 28, percent_over_25_without_HS_diploma: 29, percent_under_18_over_64: 43, per_capita_income: 11888, hardship_index: 94},
  {community_area: 69, community_area_name: "Greater Grand Crossing", percent_of_housing_crowded: 4, percent_households_below_poverty: 30, percent_over_16_unemployed: 23, percent_over_25_without_HS_diploma: 17, percent_under_18_over_64: 41, per_capita_income: 17285, hardship_index: 66},
  {community_area: 70, community_area_name: "Ashburn", percent_of_housing_crowded: 4, percent_households_below_poverty: 10, percent_over_16_unemployed: 12, percent_over_25_without_HS_diploma: 18, percent_under_18_over_64: 37, per_capita_income: 23482, hardship_index: 37},
  {community_area: 71, community_area_name: "Auburn Gresham", percent_of_housing_crowded: 4, percent_households_below_poverty: 28, percent_over_16_unemployed: 28, percent_over_25_without_HS_diploma: 19, percent_under_18_over_64: 42, per_capita_income: 15528, hardship_index: 74},
  {community_area: 72, community_area_name: "Beverly", percent_of_housing_crowded: 1, percent_households_below_poverty: 5, percent_over_16_unemployed: 8, percent_over_25_without_HS_diploma: 4, percent_under_18_over_64: 41, per_capita_income: 39523, hardship_index: 12},
  {community_area: 73, community_area_name: "Washington Height", percent_of_housing_crowded: 1, percent_households_below_poverty: 17, percent_over_16_unemployed: 21, percent_over_25_without_HS_diploma: 14, percent_under_18_over_64: 43, per_capita_income: 19713, hardship_index: 48},
  {community_area: 74, community_area_name: "Mount Greenwood", percent_of_housing_crowded: 1, percent_households_below_poverty: 3, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 4, percent_under_18_over_64: 37, per_capita_income: 34381, hardship_index: 16},
  {community_area: 75, community_area_name: "Morgan Park", percent_of_housing_crowded: 1, percent_households_below_poverty: 13, percent_over_16_unemployed: 15, percent_over_25_without_HS_diploma: 11, percent_under_18_over_64: 40, per_capita_income: 27149, hardship_index: 30},
  {community_area: 76, community_area_name: "O'Hare", percent_of_housing_crowded: 4, percent_households_below_poverty: 15, percent_over_16_unemployed: 7, percent_over_25_without_HS_diploma: 11, percent_under_18_over_64: 30, per_capita_income: 25828, hardship_index: 24},
  {community_area: 77, community_area_name: "Edgewater", percent_of_housing_crowded: 4, percent_households_below_poverty: 18, percent_over_16_unemployed: 9, percent_over_25_without_HS_diploma: 10, percent_under_18_over_64: 24, per_capita_income: 33385, hardship_index: 19},
  {community_area: nil, community_area_name: "CHICAGO", percent_of_housing_crowded: 5, percent_households_below_poverty: 20, percent_over_16_unemployed: 13, percent_over_25_without_HS_diploma: 20, percent_under_18_over_64: 34, per_capita_income: 28202, hardship_index: nil}
])
VacantProperty.create!([
  {community_area: 1, number_of_vacant_properties: 10},
  {community_area: 2, number_of_vacant_properties: 4},
  {community_area: 3, number_of_vacant_properties: 5},
  {community_area: 4, number_of_vacant_properties: 12},
  {community_area: 5, number_of_vacant_properties: 6},
  {community_area: 7, number_of_vacant_properties: 14},
  {community_area: 8, number_of_vacant_properties: 17},
  {community_area: 11, number_of_vacant_properties: 2},
  {community_area: 14, number_of_vacant_properties: 12},
  {community_area: 15, number_of_vacant_properties: 13},
  {community_area: 16, number_of_vacant_properties: 2},
  {community_area: 17, number_of_vacant_properties: 2},
  {community_area: 19, number_of_vacant_properties: 5},
  {community_area: 20, number_of_vacant_properties: 3},
  {community_area: 21, number_of_vacant_properties: 7},
  {community_area: 22, number_of_vacant_properties: 20},
  {community_area: 23, number_of_vacant_properties: 462},
  {community_area: 24, number_of_vacant_properties: 39},
  {community_area: 25, number_of_vacant_properties: 413},
  {community_area: 26, number_of_vacant_properties: 452},
  {community_area: 27, number_of_vacant_properties: 758},
  {community_area: 28, number_of_vacant_properties: 287},
  {community_area: 29, number_of_vacant_properties: 1100},
  {community_area: 30, number_of_vacant_properties: 77},
  {community_area: 31, number_of_vacant_properties: 24},
  {community_area: 32, number_of_vacant_properties: 10},
  {community_area: 33, number_of_vacant_properties: 18},
  {community_area: 34, number_of_vacant_properties: 5},
  {community_area: 35, number_of_vacant_properties: 118},
  {community_area: 36, number_of_vacant_properties: 120},
  {community_area: 37, number_of_vacant_properties: 269},
  {community_area: 38, number_of_vacant_properties: 642},
  {community_area: 39, number_of_vacant_properties: 79},
  {community_area: 40, number_of_vacant_properties: 540},
  {community_area: 41, number_of_vacant_properties: 3},
  {community_area: 42, number_of_vacant_properties: 434},
  {community_area: 43, number_of_vacant_properties: 179},
  {community_area: 44, number_of_vacant_properties: 91},
  {community_area: 45, number_of_vacant_properties: 23},
  {community_area: 46, number_of_vacant_properties: 545},
  {community_area: 47, number_of_vacant_properties: 32},
  {community_area: 48, number_of_vacant_properties: 20},
  {community_area: 49, number_of_vacant_properties: 411},
  {community_area: 50, number_of_vacant_properties: 36},
  {community_area: 51, number_of_vacant_properties: 372},
  {community_area: 52, number_of_vacant_properties: 46},
  {community_area: 53, number_of_vacant_properties: 475},
  {community_area: 54, number_of_vacant_properties: 188},
  {community_area: 55, number_of_vacant_properties: 66},
  {community_area: 56, number_of_vacant_properties: 17},
  {community_area: 57, number_of_vacant_properties: 6},
  {community_area: 58, number_of_vacant_properties: 12},
  {community_area: 59, number_of_vacant_properties: 9},
  {community_area: 60, number_of_vacant_properties: 22},
  {community_area: 61, number_of_vacant_properties: 1176},
  {community_area: 63, number_of_vacant_properties: 9},
  {community_area: 64, number_of_vacant_properties: 9},
  {community_area: 65, number_of_vacant_properties: 5},
  {community_area: 66, number_of_vacant_properties: 42},
  {community_area: 67, number_of_vacant_properties: 1128},
  {community_area: 68, number_of_vacant_properties: 1694},
  {community_area: 69, number_of_vacant_properties: 366},
  {community_area: 70, number_of_vacant_properties: 25},
  {community_area: 71, number_of_vacant_properties: 240},
  {community_area: 72, number_of_vacant_properties: 5},
  {community_area: 73, number_of_vacant_properties: 50},
  {community_area: 75, number_of_vacant_properties: 130}
])
