json.community_area life_expectancy.community_area
json.community_area_name life_expectancy.community_area_name

json.life_expectancy_1990 life_expectancy.life_expectancy_1990
json.life_expectancy_2000 life_expectancy.life_expectancy_2000
json.life_expectancy_2010 life_expectancy.life_expectancy_2010



